/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Outlines, useGLTF } from "@react-three/drei";

export default function Model({
  outlined,
  ...props
}: {
  outlined: boolean;
} & JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/rock/model.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.menhir_mini.geometry}>
        <meshStandardMaterial
          attach="material"
          color="gray"
          roughness={10}
          metalness={0.3}
        />
        {outlined && <Outlines thickness={0.1} color="yellow" />}
      </mesh>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/rock/model.gltf"
);
